// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC29CZwbKIlB--gPxbLriFPKudJYQBskK8',
    appId: '1:157772513866:web:07be42d9654842500a5cb3',
    messagingSenderId: '157772513866',
    projectId: 'lenz-ade22',
    authDomain: 'lenz-ade22.firebaseapp.com',
    storageBucket: 'lenz-ade22.firebasestorage.app',
    measurementId: 'G-3VFCM74031',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Qn5Ulb76u3giXcqN791rzHvjdCKofTE',
    appId: '1:157772513866:android:5dc9ed3818de75e00a5cb3',
    messagingSenderId: '157772513866',
    projectId: 'lenz-ade22',
    storageBucket: 'lenz-ade22.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC00-wDR_3DfeQCjqjoesKccn_K4TC0jfw',
    appId: '1:157772513866:ios:1e4231dd3a5a4d580a5cb3',
    messagingSenderId: '157772513866',
    projectId: 'lenz-ade22',
    storageBucket: 'lenz-ade22.firebasestorage.app',
    androidClientId: '157772513866-v1ilp8trg71vc6788h965259nmgdpnpm.apps.googleusercontent.com',
    iosClientId: '157772513866-g880scvsdb8jbmvpsvo4s1eatl84kugk.apps.googleusercontent.com',
    iosBundleId: 'com.veradostudio.replicaDetector',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC00-wDR_3DfeQCjqjoesKccn_K4TC0jfw',
    appId: '1:157772513866:ios:1e4231dd3a5a4d580a5cb3',
    messagingSenderId: '157772513866',
    projectId: 'lenz-ade22',
    storageBucket: 'lenz-ade22.firebasestorage.app',
    iosBundleId: 'com.veradostudio.replicaDetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC29CZwbKIlB--gPxbLriFPKudJYQBskK8',
    appId: '1:157772513866:web:37bfdcb7fedc8cfa0a5cb3',
    messagingSenderId: '157772513866',
    projectId: 'lenz-ade22',
    authDomain: 'lenz-ade22.firebaseapp.com',
    storageBucket: 'lenz-ade22.firebasestorage.app',
    measurementId: 'G-KCPRCQFFNW',
  );
}
